### ISSUE TITLE
程序无法运行(疑似网络连接问题?)

### ISSUE THREAD

**Issue by YukishiroKarin** [v03413/bepusdt#17]
错误日志
`SIGSEGV: segmentation violation
PC=0x7f3392616372 m=4 sigcode=1
signal arrived during cgo execution

goroutine 9 [syscall]:
runtime.cgocall(0xb73e00, 0xc000048d88)
        runtime/cgocall.go:157 +0x4b fp=0xc000048d60 sp=0xc000048d28 pc=0x4094cb
net._C2func_getaddrinfo(0xc0003cae88, 0x0, 0xc000520600, 0xc000032450)
        _cgo_gotypes.go:100 +0x55 fp=0xc000048d88 sp=0xc000048d60 pc=0x59c555
net._C_getaddrinfo.func1(0x4124a5?, 0x8?, 0xc9c9a0?, 0x1?)
        net/cgo_unix_cgo.go:78 +0x7a fp=0xc000048df0 sp=0xc000048d88 pc=0x59c91a
net._C_getaddrinfo(0xc0003cad98?, 0x10?, 0x0?, 0x0?)
        net/cgo_unix_cgo.go:78 +0x13 fp=0xc000048e20 sp=0xc000048df0 pc=0x59c853
net.cgoLookupHostIP({0xd9202c, 0x3}, {0xc0003cad98, 0x10})
        net/cgo_unix.go:166 +0x24f fp=0xc000048f60 sp=0xc000048e20 pc=0x5724af
net.cgoLookupIP.func1()
        net/cgo_unix.go:215 +0x25 fp=0xc000048f90 sp=0xc000048f60 pc=0x572bc5
net.doBlockingWithCtx[...].func1()
        net/cgo_unix.go:56 +0x35 fp=0xc000048fe0 sp=0xc000048f90 pc=0x59cbd5
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc000048fe8 sp=0xc000048fe0 pc=0x46dbe1
created by net.doBlockingWithCtx[...] in goroutine 8
        net/cgo_unix.go:54 +0xd8

goroutine 1 [select, locked to thread]:
runtime.gopark(0xc00041efa8?, 0x4?, 0x10?, 0xed?, 0xc00041ee50?)
        runtime/proc.go:398 +0xce fp=0xc000530cc8 sp=0xc000530ca8 pc=0x43e06e
runtime.selectgo(0xc000530fa8, 0xc00041ee48, 0xc0004e3370?, 0x0, 0xc00041eec8?, 0x1)
        runtime/select.go:327 +0x725 fp=0xc000530de8 sp=0xc000530cc8 pc=0x44dba5
net/http.(*Transport).getConn(0x1346e00, 0xc0004d9400, {{}, 0x0, {0xc000031360, 0x5}, {0xc0003cad98, 0x14}, 0x0})
        net/http/transport.go:1393 +0x5b3 fp=0xc000531000 sp=0xc000530de8 pc=0x810d53
net/http.(*Transport).roundTrip(0x1346e00, 0xc0002df800)
        net/http/transport.go:591 +0x73a fp=0xc000531228 sp=0xc000531000 pc=0x80ccfa
net/http.(*Transport).RoundTrip(0x426b28?, 0xebd380?)
        net/http/roundtrip.go:17 +0x13 fp=0xc000531248 sp=0xc000531228 pc=0x7f5933
net/http.send(0xc0002df800, {0xebd380, 0x1346e00}, {0xc00041f401?, 0x462885?, 0x0?})
        net/http/client.go:260 +0x606 fp=0xc000531478 sp=0xc000531248 pc=0x7b1d06
net/http.(*Client).send(0xc0004e9f20, 0xc0002df800, {0x90?, 0x1?, 0x0?})
        net/http/client.go:181 +0x98 fp=0xc0005314f0 sp=0xc000531478 pc=0x7b1598
net/http.(*Client).do(0xc0004e9f20, 0xc0002df800)
        net/http/client.go:724 +0x912 fp=0xc000531700 sp=0xc0005314f0 pc=0x7b3872
net/http.(*Client).Do(0xd3d7c0?, 0xc0004e9f50?)
        net/http/client.go:590 +0x13 fp=0xc000531720 sp=0xc000531700 pc=0x7b2f33
github.com/go-telegram-bot-api/telegram-bot-api/v5.(*BotAPI).MakeRequest(0xc0005130e0, {0xd93abc, 0x5}, 0x0)
        github.com/go-telegram-bot-api/telegram-bot-api/v5@v5.5.1/bot.go:110 +0x451 fp=0xc000531bf0 sp=0xc000531720 pc=0x83b911
github.com/go-telegram-bot-api/telegram-bot-api/v5.(*BotAPI).GetMe(0x2?)
        github.com/go-telegram-bot-api/telegram-bot-api/v5@v5.5.1/bot.go:285 +0x47 fp=0xc000531c38 sp=0xc000531bf0 pc=0x83cf67
github.com/go-telegram-bot-api/telegram-bot-api/v5.NewBotAPIWithClient({0xc00002e04d, 0x2e}, {0xdb3b58, 0x21}, {0xebd440?, 0xc0004e9f20})
        github.com/go-telegram-bot-api/telegram-bot-api/v5@v5.5.1/bot.go:65 +0x178 fp=0xc000531d70 sp=0xc000531c38 pc=0x83b378
github.com/go-telegram-bot-api/telegram-bot-api/v5.NewBotAPI(...)
        github.com/go-telegram-bot-api/telegram-bot-api/v5@v5.5.1/bot.go:40
github.com/v03413/bepusdt/app/telegram.init.0()
        github.com/v03413/bepusdt/app/telegram/telegram.go:20 +0x65 fp=0xc000531e10 sp=0xc000531d70 pc=0x846ac5
runtime.doInit1(0x1358380)
        runtime/proc.go:6740 +0xd8 fp=0xc000531f40 sp=0xc000531e10 pc=0x44adb8
runtime.doInit(...)
        runtime/proc.go:6707
runtime.main()
        runtime/proc.go:249 +0x374 fp=0xc000531fe0 sp=0xc000531f40 pc=0x43dcd4
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc000531fe8 sp=0xc000531fe0 pc=0x46dbe1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:398 +0xce fp=0xc000046fa8 sp=0xc000046f88 pc=0x43e06e
runtime.goparkunlock(...)
        runtime/proc.go:404
runtime.forcegchelper()
        runtime/proc.go:322 +0xb3 fp=0xc000046fe0 sp=0xc000046fa8 pc=0x43def3
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc000046fe8 sp=0xc000046fe0 pc=0x46dbe1
created by runtime.init.6 in goroutine 1
        runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:398 +0xce fp=0xc000047778 sp=0xc000047758 pc=0x43e06e
runtime.goparkunlock(...)
        runtime/proc.go:404
runtime.bgsweep(0x0?)
        runtime/mgcsweep.go:321 +0xdf fp=0xc0000477c8 sp=0xc000047778 pc=0x429fbf
runtime.gcenable.func1()
        runtime/mgc.go:200 +0x25 fp=0xc0000477e0 sp=0xc0000477c8 pc=0x41f0e5
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc0000477e8 sp=0xc0000477e0 pc=0x46dbe1
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000066000?, 0xeb7b70?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:398 +0xce fp=0xc000047f70 sp=0xc000047f50 pc=0x43e06e
runtime.goparkunlock(...)
        runtime/proc.go:404
runtime.(*scavengerState).park(0x139ec40)
        runtime/mgcscavenge.go:425 +0x49 fp=0xc000047fa0 sp=0xc000047f70 pc=0x4277e9
runtime.bgscavenge(0x0?)
        runtime/mgcscavenge.go:658 +0x59 fp=0xc000047fc8 sp=0xc000047fa0 pc=0x427d99
runtime.gcenable.func2()
        runtime/mgc.go:201 +0x25 fp=0xc000047fe0 sp=0xc000047fc8 pc=0x41f085
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc000047fe8 sp=0xc000047fe0 pc=0x46dbe1
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:201 +0xa5

goroutine 5 [finalizer wait]:
runtime.gopark(0xd8b7a0?, 0x10043f201?, 0x0?, 0x0?, 0x446225?)
        runtime/proc.go:398 +0xce fp=0xc000046628 sp=0xc000046608 pc=0x43e06e
runtime.runfinq()
        runtime/mfinal.go:193 +0x107 fp=0xc0000467e0 sp=0xc000046628 pc=0x41e167
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc0000467e8 sp=0xc0000467e0 pc=0x46dbe1
created by runtime.createfing in goroutine 1
        runtime/mfinal.go:163 +0x3d

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x33b251f332?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:398 +0xce fp=0xc000048750 sp=0xc000048730 pc=0x43e06e
runtime.gcBgMarkWorker()
        runtime/mgc.go:1293 +0xe5 fp=0xc0000487e0 sp=0xc000048750 pc=0x420c65
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc0000487e8 sp=0xc0000487e0 pc=0x46dbe1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        runtime/mgc.go:1217 +0x1c

goroutine 7 [select]:
runtime.gopark(0xc000537578?, 0x2?, 0x8?, 0x41?, 0xc0005374d4?)
        runtime/proc.go:398 +0xce fp=0xc000537320 sp=0xc000537300 pc=0x43e06e
runtime.selectgo(0xc000537578, 0xc0005374d0, 0x14?, 0x0, 0x0?, 0x1)
        runtime/select.go:327 +0x725 fp=0xc000537440 sp=0xc000537320 pc=0x44dba5
net.(*Resolver).lookupIPAddr(0x139e000, {0xec20c0?, 0xc000515b20}, {0xd9202c, 0x3}, {0xc0003cad98, 0x10})
        net/lookup.go:332 +0x3fe fp=0xc000537620 sp=0xc000537440 pc=0x58b4de
net.(*Resolver).internetAddrList(0xec20c0?, {0xec20c0?, 0xc000515b20?}, {0xd9202c, 0x3}, {0xc0003cad98?, 0x4f8d05?})
        net/ipsock.go:288 +0x4e5 fp=0xc000537748 sp=0xc000537620 pc=0x5894e5
net.(*Resolver).resolveAddrList(0x13d4f00?, {0xec20c0, 0xc000515b20}, {0xd92c0a, 0x4}, {0xd9202c?, 0x0?}, {0xc0003cad98, 0x14}, {0x0, ...})
        net/dial.go:282 +0x405 fp=0xc000537848 sp=0xc000537748 pc=0x574dc5
net.(*Dialer).DialContext(0xc000515ab0, {0xec1e58, 0x13d4f00}, {0xd9202c, 0x3}, {0xc0003cad98, 0x14})
        net/dial.go:488 +0x42c fp=0xc000537980 sp=0xc000537848 pc=0x575b6c
net.(*Dialer).DialContext-fm({0xec1e58?, 0x13d4f00?}, {0xd9202c?, 0xc00004ac00?}, {0xc0003cad98?, 0x0?})
        <autogenerated>:1 +0x49 fp=0xc0005379c8 sp=0xc000537980 pc=0x825309
net/http.(*Transport).dial(0x0?, {0xec1e58?, 0x13d4f00?}, {0xd9202c?, 0x0?}, {0xc0003cad98?, 0x0?})
        net/http/transport.go:1183 +0xd2 fp=0xc000537a30 sp=0xc0005379c8 pc=0x810092
net/http.(*Transport).dialConn(0x1346e00, {0xec1e58, 0x13d4f00}, {{}, 0x0, {0xc000031360, 0x5}, {0xc0003cad98, 0x14}, 0x0})
        net/http/transport.go:1625 +0x7e8 fp=0xc000537ed8 sp=0xc000537a30 pc=0x812e48
net/http.(*Transport).dialConnFor(0x0?, 0xc0000a8840)
        net/http/transport.go:1467 +0x9f fp=0xc000537fc0 sp=0xc000537ed8 pc=0x81195f
net/http.(*Transport).queueForDial.func1()
        net/http/transport.go:1436 +0x25 fp=0xc000537fe0 sp=0xc000537fc0 pc=0x811885
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc000537fe8 sp=0xc000537fe0 pc=0x46dbe1
created by net/http.(*Transport).queueForDial in goroutine 1
        net/http/transport.go:1436 +0x3cb

goroutine 8 [select]:
runtime.gopark(0xc000539b50?, 0x2?, 0x78?, 0x9b?, 0xc000539b34?)
        runtime/proc.go:398 +0xce fp=0xc0005399e0 sp=0xc0005399c0 pc=0x43e06e
runtime.selectgo(0xc000539b50, 0xc000539b30, 0x0?, 0x0, 0x0?, 0x1)
        runtime/select.go:327 +0x725 fp=0xc000539b00 sp=0xc0005399e0 pc=0x44dba5
net.doBlockingWithCtx[...]({0xec2050, 0xc0004eed70}, 0xc0005205a0)
        net/cgo_unix.go:60 +0x14f fp=0xc000539bd0 sp=0xc000539b00 pc=0x59e3af
net.cgoLookupIP({0xec2050, 0xc0004eed70}, {0xd9202c, 0x3}, {0xc0003cad98, 0x10})
        net/cgo_unix.go:214 +0xb4 fp=0xc000539c00 sp=0xc000539bd0 pc=0x572b34
net.(*Resolver).lookupIP(0x139e000, {0xec2050, 0xc0004eed70}, {0xd9202c, 0x3}, {0xc0003cad98, 0x10})
        net/lookup_unix.go:70 +0x11a fp=0xc000539e58 sp=0xc000539c00 pc=0x58c91a
net.(*Resolver).lookupIP-fm({0xec2050?, 0xc0004eed70?}, {0xd9202c?, 0x0?}, {0xc0003cad98?, 0x81476a?})
        <autogenerated>:1 +0x49 fp=0xc000539ea0 sp=0xc000539e58 pc=0x5a1209
net.glob..func1({0xec2050?, 0xc0004eed70?}, 0x0?, {0xd9202c?, 0x5?}, {0xc0003cad98?, 0x14?})
        net/hook.go:23 +0x37 fp=0xc000539ee0 sp=0xc000539ea0 pc=0x581f37
net.(*Resolver).lookupIPAddr.func1()
        net/lookup.go:324 +0x3a fp=0xc000539f38 sp=0xc000539ee0 pc=0x58befa
internal/singleflight.(*Group).doCall(0x139e010, 0xc0004eedc0, {0xc0003ca678, 0x14}, 0xc0000a8840?)
        internal/singleflight/singleflight.go:93 +0x35 fp=0xc000539fa8 sp=0xc000539f38 pc=0x570035
internal/singleflight.(*Group).DoChan.func1()
        internal/singleflight/singleflight.go:86 +0x30 fp=0xc000539fe0 sp=0xc000539fa8 pc=0x56ffd0
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc000539fe8 sp=0xc000539fe0 pc=0x46dbe1
created by internal/singleflight.(*Group).DoChan in goroutine 7
        internal/singleflight/singleflight.go:86 +0x2e9

rax    0x1d3560
rbx    0x0
rcx    0xffffffffffffff10
rdx    0x7f3392730bf0
rdi    0x0
rsi    0xf1755d
rbp    0x4
rsp    0x7f33939db018
r8     0x963cf85
r9     0x0
r10    0x6e
r11    0x7f3388000090
r12    0x7f3388003220
r13    0x1
r14    0x7f33880010c0
r15    0x7f3388003220
rip    0x7f3392616372
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0
`
已经查机器是可以正常和api.telegram.org进行通信

**Comment by v03413** [comment]
使用海外服务器，确保DNS解析是正常的

**Comment by YukishiroKarin** [comment]
> 使用海外服务器，确保DNS解析是正常的

是使用海外服务器，服务器为AWS日本
这次我是重新部署，之前也是使用AWS日本没有遇到问题，但是我尝试使用了Azure日本就没有遇到问题（AWS日本系统为Debian12，Azure系统为Debian11）
DNS为默认，与telegram和okx使用wget能正常获取到内容

**Comment by YukishiroKarin** [comment]
尝试更改DNS为8.8.8.8和1.1.1.1，故障依旧

**Comment by YukishiroKarin** [comment]
> 使用海外服务器，确保DNS解析是正常的

经过多次调试，已自行解决问题，并非网络连接问题，确定是由于系统原因导致
因为我使用Debian12系统，可能是因为内核版本高，库等行为上的差异。无法运行，通过将项目克隆到本地进行手动编译，成功解决了问题。
### 解决方法
安装go1.22.2版本，使用git将项目克隆到本地，进行编译
`CGO_ENABLED=1 go build -trimpath -ldflags="-linkmode external -extldflags -static -s -w -buildid=" -o bepusdt ./main`
