### ISSUE TITLE
Some issues about Telegram Bot..

### ISSUE THREAD

**Issue by StevenLyo** [v03413/bepusdt#18]
Well, i've successfully built up a BEPUSDT system and configure telegram bot. But what i've encountered was a "❌query failed" problem when i added a new wallet to the bot i've created. I tried several wallets from different organizations, but it still occurred. 

How to solve this problem? Thx

**Comment by v03413** [comment]
> Well, i've successfully built up a BEPUSDT system and configure telegram bot. But what i've encountered was a "❌query failed" problem when i added a new wallet to the bot i've created. I tried several wallets from different organizations, but it still occurred.
> 
> How to solve this problem? Thx

I guess, maybe there is an issue with your USDT.TRX address.
