### ISSUE TITLE
部署完成但是没反应？

### ISSUE THREAD

**Issue by annypay** [v03413/bepusdt#19]
![image](https://github.com/v03413/bepusdt/assets/148721999/14329023-e7ce-4fcb-9eb7-a8f70745314d)
部署都一切正常
目前这个没反应。
但是IP:8080能够看到正常运行的云朵画面。
而且TG里面所有的指令都没反馈。

**Comment by v03413** [comment]
给出详细日志

**Comment by xia-shangzhou** [comment]
> 给出详细日志

2024/06/29 22:58:19 Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2024/06/29 22:58:19 Failed to get updates, retrying in 3 seconds...

我用docker部署的，运行后也是上面那样，输入/start没有反应。检查docker日志提示上面那些

**Comment by v03413** [comment]
猜测是 bot 运行方式冲突，已尝试解决 https://github.com/v03413/bepusdt/commit/407fad6e75a43e9a29f22bc7ee375f211d3d8922 没什么问题本 issue 关闭
