### ISSUE TITLE
能不能提供一个接口文档

### ISSUE THREAD

**Issue by hei2077** [v03413/bepusdt#21]
能不能提供一个接口文档，一直提示400，参数错误，不知道是哪里有问题

**Comment by v03413** [comment]
<img width="465" alt="image" src="https://github.com/v03413/bepusdt/assets/49953737/549a6257-2bb1-4e8d-a62d-661b23b4b431">  
文档有空再更新，确保这几个参数正确提交。

**Comment by hei2077** [comment]
> <img alt="image" width="465" src="https://private-user-images.githubusercontent.com/49953737/331777713-549a6257-2bb1-4e8d-a62d-661b23b4b431.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNDMwMzUsIm5iZiI6MTcxNjE0MjczNSwicGF0aCI6Ii80OTk1MzczNy8zMzE3Nzc3MTMtNTQ5YTYyNTctMmJiMS00ZThkLWE2MmQtNjYxYjIzYjRiNDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDE4MTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MDMwODczYmNlOWQ2MDVkYjljYTRlNzJlYjczYjQyZmU1NjM4NTIzMDc5M2RlYTllYmU1N2FkN2Q3MDU1YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IkJAF0YFURKS93BPNwkS4cV-BE1HWuE1g8h5qJWwVmQ"> 文档有空再更新，确保这几个参数正确提交。

---
谢谢，没事了，已找到报错的原因，我提交的 amount 参数的值用的是字符串格式
