### ISSUE TITLE
并发下创建交易会存在相同金额

### ISSUE THREAD

**Issue by echo-ix** [v03413/bepusdt#27]
并发创建10CNY金额，汇率为1的交易订单，返回的实际需要支付的金额actual_amount会出现相同金额，保证不了并发，并且金额不是4为小数，修改源码Atomicity之后才会0.0001开始自增。

**Comment by v03413** [comment]
当初写的时候有考虑过并发问题，但是细想有并发需求的**应该或许可能**不会用这个吧，于是就没深入细写。🤔  
而至于精度问题 常量  Atomicity，当初是考虑到大部分交易所和交易场景都是两位小数，虽然也有考虑过自定义引入；但 忙 + 拖延症 没动力就耽搁啦。  

不过感谢有人反馈了这些问题，后续调整会优先考虑。

**Comment by v03413** [comment]
> 并发创建10CNY金额，汇率为1的交易订单，返回的实际需要支付的金额actual_amount会出现相同金额，保证不了并发，并且金额不是4为小数，修改源码Atomicity之后才会0.0001开始自增。

不过您可以给出稍微详细点的压力方法吗，我尝试复现

**Comment by v03413** [comment]
此 issue 先关掉，遇到同样问题的，提供相关日志或具体信息后可 reopen
