### ISSUE TITLE
USDT汇率功能出现错误

### ISSUE THREAD

**Issue by YukishiroKarin** [v03413/bepusdt#39]
USDT_RATE数值留空仍然是默认值6.4，非Okx交易所获取的实时汇率。
并且汇率计算并不正确 基准汇率为7.21按照该费率计算出40CNY应为5.55USDT，但支付发起的是6.25USDT

包括+，-，~的计算也有错误，我使用+0.2甚至价格还变少了，成了5.4USDT
![image](https://github.com/user-attachments/assets/792d7880-176b-4c22-b867-6446b9fa5eb2)

**Comment by v03413** [comment]
感觉配置错误的可能性比较大 
<img width="88" alt="image" src="https://github.com/user-attachments/assets/2bf72017-345e-468f-babd-cb7cdfeee7d1">

**Comment by YukishiroKarin** [comment]
> 感觉配置错误的可能性比较大 <img alt="image" width="88" src="https://private-user-images.githubusercontent.com/49953737/391309356-2bf72017-345e-468f-babd-cb7cdfeee7d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMzYyMzUsIm5iZiI6MTczMzAzNTkzNSwicGF0aCI6Ii80OTk1MzczNy8zOTEzMDkzNTYtMmJmNzIwMTctMzQ1ZS00NjhmLWJhYmQtY2I3Y2RmZWVlN2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDA2NTIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhODBiN2FlYjNkYWQ5YzAyOTYzYzEzODk1NTE2MmY0MDIzNjRhNjNkYTYzNTQ3YzFjNzk4ZTZkZDgzMWQ2NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KN2fzCS_XpPtS5SN31OLp-mbs9ovtBwoH40lPwMznP4">

这是在USDT_RATE留空下的配置，查询实际浮动汇率仍然是6.4，并非Okx实时汇率。发起支付也是6.25USDT
![image](https://github.com/user-attachments/assets/df3160ae-e403-4235-9c28-675c1159064e)
![image](https://github.com/user-attachments/assets/e4721b83-5c3d-4de5-9422-d24c6407712f)
![image](https://github.com/user-attachments/assets/b13ec6e7-1741-418b-8e49-955e17201bdd)

**Comment by v03413** [comment]
已尝试修复，可试试新版 https://github.com/v03413/bepusdt/releases/tag/v1.13.32

**Comment by YukishiroKarin** [comment]
> 已尝试修复，可试试新版 https://github.com/v03413/bepusdt/releases/tag/v1.13.32

此次更新将支付界面的模版文件内置了？修改源文件无效，实测直接删除templates也可以正常发起支付

**Comment by v03413** [comment]
> > 已尝试修复，可试试新版 https://github.com/v03413/bepusdt/releases/tag/v1.13.32
> 
> 此次更新将支付界面的模版文件内置了？修改源文件无效，实测直接删除templates也可以正常发起支付

新版 是
